### ISSUE TITLE
xcode 8.1 swift 3.0.1编译不过

### ISSUE THREAD

**Issue by yinchaoyu** [fancymax/12306ForMac#117]
建议还是使用cocoapods管理，swift4.0之前ABI不稳定

**Comment by fancymax** [comment]
@yinchaoyu 你咋升那么快，8.0都能编过，8.1就编不过啦，真TM坑。
小项目还是直接Framework简单点吧，也就再麻烦那么几次。

**Comment by shenfu1991** [comment]
同样 8.1报错，信息如下：module complied with Swift 3.0 cannot be imported in Swift 3.0.1....
