### ISSUE TITLE
JSON 未能读取数据, 因为格式不正确

### ISSUE THREAD

**Issue by massacreformash** [fancymax/12306ForMac#142]
无法刷新车票, toast报错显示:"JSON 未能读取数据, 因为格式不正确"

**Comment by fancymax** [comment]
@massacreformash  我这边测试 设置自动查询，每隔10秒会抱这样的错误（其实就是空数据），暂时不影响使用。

**Comment by fancymax** [comment]
@massacreformash 测试了一下 其实是被封IP了，高峰的时候请求稍快就被封，被封之后就是容易返回空数据。
