### ISSUE TITLE
增加选择几个日期同时开始自动查票

### ISSUE THREAD

**Issue by kedu** [fancymax/12306ForMac#145]

**Comment by fancymax** [comment]
不支持 多个地点多个日期同时自动查票。

原因在于：这样做当然是最灵活的，但是由于12306的限制多轮次的查票最好用串行的方式，如果组合太多查询到某一轮次的时间间隔就太长了。

所以简单来说直接支持三个轮次 也就是三个相近日期的查询即可，实现起来也非常简单，也贴近实际的使用情况。

**Comment by fancymax** [comment]
交互方案：

12306ForMac多日期查询

- 按Ctrl多选日期，选中的日期都用红色表示
- 不按Ctrl选择日期后，取消之前的所有多选状态。
- 多个日期，则在抢票模式下 多个轮次串行查询
- 多个日期，如果在普通模式下，则每次查询之后在多选的日期中切换
- 出发日期标识一下，比如 出发日期1 xx；出发日期2 xx
- stepper控件去掉

**Comment by fancymax** [comment]
https://github.com/fancymax/12306ForMac/commit/c7a4441291176bc9cc7f0519c678de1ee7b7e708
