### ISSUE TITLE
[!] Unable to find a specification for `Alamofire (~> 4.0.0)`

### ISSUE THREAD

**Issue by lianxingbo** [fancymax/12306ForMac#149]
localhost:12306ForMac zhihuibutong$ pod install
Analyzing dependencies
[!] Unable to find a specification for `Alamofire (~> 4.0.0)`

**Comment by fancymax** [comment]
善用搜索哈。。

https://github.com/Alamofire/Alamofire/issues/1727

**Comment by lianxingbo** [comment]
我个人已经解决了，我提这个issues是提醒你项目打不开有问题，你写这个的目的不就是为了帮助别人mac上用12306吗不是，每个人代码下下来打开报错是不是很不爽啊。。
