### ISSUE TITLE
（求教）关于验证码校验请求的问题

### ISSUE THREAD

**Issue by fvaryu** [fancymax/12306ForMac#154]
看了你的代码我用Android也写了下，但是在校验验证码那步有问题，一直不知道原因，问题如下：
我随便输入验证码：
` .add("randCode", "40,40")
                        .add("rand", "sjrand")`
返回结果是：
`{"validateMessagesShowId":"_validatorMessage","status":true,"httpstatus":200,"data":{"result":"0","msg":""},"messages":[],"validateMessages":{}}`
里面的msg字段为什么不是False，用Fiddler看了官网的，如果输入验证码是错的，那么msg=False。

分析：
Fiddler中的randCode参数值好像是经过编码了e.g. randCode=40%CD4A%40&rand=sjrand，但是你的代码中也没这一步，不知道为什么？

另外：你的请求头中refer是什么意思，重定向吗？重定向的头不是应该是Referer吗？

ps：iOS不是太会，还请指点一二，谢谢！

**Comment by fancymax** [comment]
@fvaryu 可以看一下这个教程

https://blog.fishlee.net/tag/ticket-12306-demo/
