### ISSUE TITLE
已经登录账号了，当检测到有票时候还是需要登录

### ISSUE THREAD

**Issue by renzifeng** [fancymax/12306ForMac#156]
12306的登录是不是有失效时间呀

**Comment by fancymax** [comment]
@renzifeng 是的。。

高峰时间 特别容易踢。。。另外登录的时候 不能太快，否则被封IP。  提示JSON无法解析 一般就是被封IP了。

**Comment by icefed** [comment]
有时间可以研究研究mobile api, 那些要钱的抢票软件用的就是

**Comment by znoodl** [comment]
有时间可以研究研究mobile api, 那些要钱的抢票软件用的就是
