### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by fvaryu** [fancymax/12306ForMac#157]
下载下来的项目编译的时候报：no such file, Podfile.lock
然后用pod install/update的时候就停在Clone spec ...../ from 'https://git.coding.net/CocoaPods/Specs.git

**Comment by fancymax** [comment]
cocoaPods确实比较坑。

可以参考一下  http://www.jianshu.com/p/32d9cfb91471

**Comment by fvaryu** [comment]
@fancymax thx
