### ISSUE TITLE
筛选功能中纯数字的车次无法用“车次类型”来进行筛选

### ISSUE THREAD

**Issue by CloudnuY** [fancymax/12306ForMac#162]
如题
![image](https://cloud.githubusercontent.com/assets/14636247/22592510/0f51f18a-ea55-11e6-8d29-b014539a4636.png)
部分线路有纯数字车次，这里的筛选无法过滤

**Comment by fancymax** [comment]
https://github.com/fancymax/12306ForMac/commit/d18e5a2fe75df792a1cb1f04e346587a3e648a41
