### ISSUE TITLE
查询的时候必闪退啊

### ISSUE THREAD

**Issue by Onetaway** [fancymax/12306ForMac#171]
如题

**Comment by fancymax** [comment]
@Onetaway 12306查询接口修改了，这边还没改

**Comment by Alexzl5** [comment]
查询闪退。。。解决了吗？

**Comment by fancymax** [comment]
@Alexzl5 这两天看一下，昨天接口突然改了。

**Comment by fancymax** [comment]
Bug 已经处理，明天就会更新到Appstore上 @Onetaway @Alexzl5 @loadmemo

**Comment by Alexzl5** [comment]
@fancymax 谢了。。。

**Comment by Alexzl5** [comment]
还是没看到更新？？

**Comment by fancymax** [comment]
@Alexzl5 😅从昨天早上 到 现在 一直在 InReview状态

**Comment by fancymax** [comment]
#173

**Comment by fancymax** [comment]
#173

**Comment by CloudnuY** [comment]
@fancymax 可以尝试使用Travis CI自动构建然后提交到Github Releases

**Comment by fancymax** [comment]
@CloudnuY 最低的也要$39/mo 用不起啊

**Comment by CloudnuY** [comment]
@fancymax Github的公开项目是全免费的(๑•̀ㅂ•́)و✧

**Comment by fancymax** [comment]
@CloudnuY OS X Plan是要钱的，linux的plan好像有免费的
https://circleci.com/pricing/?utm_campaign=drip_2a&utm_medium=email#build-os-x

**Comment by CloudnuY** [comment]
@fancymax https://travis-ci.org/  这个呢

**Comment by fancymax** [comment]
@CloudnuY 好的，改天尝试一下。

**Comment by fancymax** [comment]
已上Mac Appstore
