### ISSUE TITLE
按双向箭头交换出发到达地后点开始查询会变回原来的出发到达地

### ISSUE THREAD

**Issue by wyix** [fancymax/12306ForMac#175]
更新了最新版，输入出发到达地址再点双向箭头交换出发到达地按开始查询会变回最开始的出发到达地

**Comment by fancymax** [comment]
@wyix 谢谢

**Comment by fancymax** [comment]
https://github.com/fancymax/12306ForMac/commit/3c4cc560c151687cf8bda6a69d9843d205876c85
