### ISSUE TITLE
Json could not be serialized 

### ISSUE THREAD

**Issue by 0x1042** [fancymax/12306ForMac#176]
![](https://ws4.sinaimg.cn/large/006tNc79ly1ffu3rqb2n5j30mw0ksq6e.jpg)

**Comment by fancymax** [comment]
@adamweixuan 刷新太快导致的

**Comment by ludawei** [comment]
@adamweixuan 遇到同样问题😭
![image](https://user-images.githubusercontent.com/4829345/29907764-064240a4-8de3-11e7-91c3-07a950e6f82b.png)

**Comment by jelinet** [comment]
@fancymax 同样的问题。。。刚开客户端刷出验证码后，需要等一会再点？无法登录。

**Comment by fancymax** [comment]
@ludawei @Jelinet 登陆的接口有变化，这两天会修改一下

**Comment by kansonkong** [comment]
一直显示这个提示，登录不了。

**Comment by HolmesZhao** [comment]
登录和查询的都变了, 之前写的脚本也不好用了

**Comment by ghost** [comment]
登录 查询都变更了。需要更新下对应接口吧。不过第一次安装使用还是可以的，但是再次使用就会出现这个问题

**Comment by huanglong6828** [comment]
@fancymax  首次使用登陆 也出现同样问题 请问一下有没有解决办法

**Comment by xpbtmusic** [comment]
https://github.com/chensijiang/qp12306/tree/master/src 我对swift不是很熟，可以参考一下这个项目，貌似接口最新的，还有需要session缓存。

**Comment by renzifeng** [comment]
作者什么时候可以改一下接口啊

**Comment by fancymax** [comment]
#179
