### ISSUE TITLE
clone了最新的代码，登录的时候验证码错误

### ISSUE THREAD

**Issue by desirelll** [fancymax/12306ForMac#179]
抢不到回家的票了呀

**Comment by cuzv** [comment]
same issue here.

**Comment by HolmesZhao** [comment]
same issue here.

**Comment by fancymax** [comment]
@desirelll @cuzv @HomlesZhao @loadmemo  目前应该已经可以订票了，可以试试～～
不过代码还需要优化一下。

**Comment by cuzv** [comment]
@fancymax 可以用了，❤️。

**Comment by HolmesZhao** [comment]
@fancymax 接口怎么爬的可以说下么😂

**Comment by fancymax** [comment]
@HomlesZhao 就是用Charles抓包，然后对照一下请求顺序，还有里面JS的逻辑。
