### ISSUE TITLE
查询乘客信息失败

### ISSUE THREAD

**Issue by AlinJiang** [fancymax/12306ForMac#188]
无法登陆，登陆显示查询乘客信息失败

**Comment by fancymax** [comment]
@AlinJiang  12306网页上的 订票帮手 里的乘车人直接无法获取了。不知道12306是不是要把这部分功能彻底废掉。

**Comment by fancymax** [comment]
@AlinJiang 今天测试了一下，就是可以的了。🐶

**Comment by AlinJiang** [comment]
谢谢，我一会试试！



-------- 原始信息 --------由： max lin <notifications@github.com> 日期: 2018/1/2  下午6:57  (GMT+08:00) 收件人： fancymax/12306ForMac <12306ForMac@noreply.github.com> 抄送： Alin <j1i2a3n4g5jiang@gmail.com>, Mention <mention@noreply.github.com> 主题： Re: [fancymax/12306ForMac] 查询乘客信息失败 (#188) 
@AlinJiang 今天测试了一下，就是可以的了。🐶

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fancymax/12306ForMac","title":"fancymax/12306ForMac","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fancymax/12306ForMac"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fancymax in #188: @AlinJiang 今天测试了一下，就是可以的了。🐶"}],"action":{"name":"View Issue","url":"https://github.com/fancymax/12306ForMac/issues/188#issuecomment-354743136"}}}
