### ISSUE TITLE
登录时提示获取验证码失败

### ISSUE THREAD

**Issue by Joey-Lee** [fancymax/12306ForMac#191]
无论怎么刷新也获取不到验证码，如图示
<img width="427" alt="2018-01-10 4 43 21" src="https://user-images.githubusercontent.com/5220341/34763303-9d150ffc-f625-11e7-8d0c-bb1654985fc0.png">

**Comment by fancymax** [comment]
@Joey-Lee 12306间歇性抽风，换手机试试吧

**Comment by fancymax** [comment]
登陆失败请到 https://github.com/fancymax/12306ForMac/releases/download/1.6.6/166.app.zip 下载新版本。
