### ISSUE TITLE
No such module 'MASPreferences'

### ISSUE THREAD

**Issue by HUALOONG** [fancymax/12306ForMac#195]
没有办法编译，提示“No such module 'MASPreferences'”

**Comment by AgoniNemo** [comment]
没有安装好依赖

**Comment by chengaojian** [comment]
@Hualoong    重新更新一下就可以了  carthage update --platform macOS

**Comment by yxwandroid** [comment]
重新更新一下就可以了 carthage update --platform macOS  
这个能给个详细的步骤吗
