### ISSUE TITLE
昨天还能正常运行，今天无法登录，更新到最新的1.6.8版本，还是报错

### ISSUE THREAD

**Issue by Joey-Lee** [fancymax/12306ForMac#201]
<img width="478" alt="2018-01-18 9 22 49" src="https://user-images.githubusercontent.com/5220341/35076216-281a7d46-fc32-11e7-98ff-12b0e8fa2f93.png">
报错如图所示

**Comment by fancymax** [comment]
@Joey-Lee 168应该是可以的

**Comment by acumen1005** [comment]
同样的错误 +1

**Comment by byrain** [comment]
取消，再重新登陆试试
我也是168，偶尔这个问题，大部分时间可以正常登陆

**Comment by Joey-Lee** [comment]
谢谢 @fancymax  @byrain  ，直接下载编译好的168可以正常运行。

**Comment by fancymax** [comment]
先参考 #192 最后的解法吧
