### ISSUE TITLE
APP Store下载的登录不上，githup下载最新工程，运行出错，求解，急！！！

### ISSUE THREAD

**Issue by MonkeyBro866** [fancymax/12306ForMac#202]
<img width="1393" alt="2018-01-18 9 54 57" src="https://user-images.githubusercontent.com/28527428/35077111-732cb174-fc36-11e7-844a-9491c99a3674.png">

**Comment by byrain** [comment]
https://github.com/fancymax/12306ForMac/releases/download/1.6.8/168.app.zip
尝试下这个版本？

**Comment by Joey-Lee** [comment]
没注意看作者用的是carthage吧，要安装依赖包先。 @sunlight0-0

**Comment by MonkeyBro866** [comment]
好的，已解决！谢谢！
