### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by SLin0218** [fancymax/12306ForMac#203]
<img width="948" alt="wx20180118-101310 2x" src="https://user-images.githubusercontent.com/23139501/35077420-3ae960bc-fc38-11e7-93fa-734b3ee2c9e2.png">

**Comment by Joey-Lee** [comment]
把报错的那句改为：
let json = try! JSON(data: dataFromString)
即可

**Comment by SLin0218** [comment]
@Joey-Lee  谢谢
