### ISSUE TITLE
卡在这了，提交订单成功，订单排队中

### ISSUE THREAD

**Issue by liyongjie1002** [fancymax/12306ForMac#212]
抢到票之后，提示提交订单成功，订单排队中，试了好几次都是这样

**Comment by iyongjie** [comment]
提交订单返回结果  

  data =     {
        count = 0;
        orderId = "<null>";
        queryOrderWaitTimeStatus = 1;
        requestId = 6364730577274687324;
        tourFlag = dc;
        waitCount = 2000;
        waitTime = 22451;
    };
    httpstatus = 200;
    messages =     (
    );
    status = 1;
    validateMessages =     {
    };
    validateMessagesShowId = "_validatorMessage";
