### ISSUE TITLE
我用其他语言写的抢票软件，但是验证验证码的时候总是返回0

### ISSUE THREAD

**Issue by coretimes** [fancymax/12306ForMac#23]
@fancymax 我用其他语言写的抢票软件，但是验证验证码的时候总是返回0，我都是浏览器截包的，应该没问题的，cookie都是浏览器一样4个cookie，但是验证验证码的时候就是失败永远返回{"validateMessagesShowId":"_validatorMessage","status":true,"httpstatus":200,"data":{"result":"0","msg":""},"messages":[],"validateMessages":{}}
困扰很久了，请问知道这是什么原因吗？

**Comment by fancymax** [comment]
@coretimes 方便的话把代码放出来看看，光凭你的描述无法推断原因

**Comment by coretimes** [comment]
@fancymax 你的邮箱是多少我发给你

**Comment by fancymax** [comment]
就在我的github首页有显示邮箱啊——！

**Comment by coretimes** [comment]
@fancymax gmail 邮箱吗，我已经发了，你看看回复一下

**Comment by fancymax** [comment]
@coretimes 除了所有请求内容尽量和web一样外，还要主要时间间隔问题。比如Web的两个请求时间间隔大概差了1秒，那你的也要遵受这歌限制。
没办法，具体的错误我们看不到只能靠猜和模范了～
