### ISSUE TITLE
没办法通过编译

### ISSUE THREAD

**Issue by MartinLau7** [fancymax/12306ForMac#35]
两个项目没有关联 编译又没通过

**Comment by fancymax** [comment]
哪两个项目没有关联？
安装pod没有？

**Comment by MartinLau7** [comment]
主项目打开后好像没法关联 pod,  pod好像没办法安装,估计是源不支持.

**Comment by fancymax** [comment]
好的，我在新电脑上试试，解决之后再和你说～

**Comment by MartinLau7** [comment]
thx, 另外告知INAppStoreWindow 其实只适合在10.9SDK 编译,之后的 SDK 框架改变了 NSWindow的 titleBarView 已经换了父类,估计你debug 的时候一直log 一些警告

**Comment by fancymax** [comment]
是的，有警告，不过使用上没什么影响。
这一版本先按照这个界面框架做。界面可能有很多不协调的地方。

之后功能稳定之后，界面会全部替换掉。

**Comment by goxofy** [comment]
求编译一个。。。

**Comment by fancymax** [comment]
@goxofy 功能不稳定，所以不想放出来，你如果需要，我可以单独发你一个

**Comment by fancymax** [comment]
@MartinLau7  两个项目没有关联的问题，修改一下 12306ForMac.xcworkspace 里的contents.xcworkspacedata就可以了，之前可能用了绝对路径，所以在你的环境无法关联。

至于pod，我用的如下的源（pod repo）

master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/lindahai/.cocoapods/repos/master

oschina-akuandev-specs
- Type: git (master)
- URL:  http://git.oschina.net/akuandev/Specs.git
- Path: /Users/lindahai/.cocoapods/repos/oschina-akuandev-specs

可以查看一下 http://blog.devtang.com/2014/05/25/use-cocoapod-to-manage-ios-lib-dependency/ 里的教程。

**Comment by renyufei8023** [comment]
os 10.10编译报错

**Comment by fancymax** [comment]
@renyufei8023  具体什么错误？检查一下 pod的配置。

**Comment by MartinLau7** [comment]
@fancymax 好的, 有空我再试试.
