### ISSUE TITLE
点着点挂了。

### ISSUE THREAD

**Issue by siosheChina** [fancymax/12306ForMac#37]
![4e559a58-b50a-4c73-92b3-20f6d0ebe21e](https://cloud.githubusercontent.com/assets/6258730/15067928/65cb4a2e-13a6-11e6-817a-c7f19f950928.png)

**Comment by fancymax** [comment]
@siosheChina 目前只有订票功能是OK的，抢票功能那个Tab还不完善，Bug应该不少。

**Comment by fancymax** [comment]
@siosheChina 可以试试一个普通的订票流程。
