### ISSUE TITLE
能否更新适配下xcode8?

### ISSUE THREAD

**Issue by liuchungui** [fancymax/12306ForMac#75]
我这里在xcode8下运行不了，Convert之后也不行

**Comment by fancymax** [comment]
暂时不会 迁移到Xcode8  @liuchungui

**Comment by liuchungui** [comment]
@fancymax 那能否放一个可运行的app包，我想体验体验

**Comment by fancymax** [comment]
@liuchungui 在Release里有啊

https://github.com/fancymax/12306ForMac/releases
