### ISSUE TITLE
xcode8 修改 podfile

### ISSUE THREAD

**Issue by ghost** [fancymax/12306ForMac#84]
# source 'http://git.oschina.net/akuandev/Specs.git'

platform :osx, '10.10'
use_frameworks!

target '12306ForMac' do
    pod 'RealmSwift'
    pod "PromiseKit", "~> 3.0”
    pod 'Alamofire', '~> 3.0'
    pod 'Fabric'
    pod 'Crashlytics'
end

关于解决 403的问题， http://git.oschina.net/akuandev/Specs  有解决方案

**Comment by lincwee** [comment]
这一段是不是没有merge到master分支上？我今天下载的代码的podfile还是老版本

**Comment by loveuqian** [comment]
这个 source 三个多月没更新了啊

**Comment by fancymax** [comment]
@vLmQm @lincwee @loveuqian 为了简单起见，移除了CocoaPods管理方式，直接下载项目即可编译
