### ISSUE TITLE
是否可以添加根据车次、发车时间、到站时间、历时分别排序的功能

### ISSUE THREAD

**Issue by HaloWang** [fancymax/12306ForMac#85]
<img width="462" alt="screen shot 2016-09-20 at 9 53 46 am" src="https://cloud.githubusercontent.com/assets/7344724/18655043/280d01a4-7f18-11e6-8343-8576b13354e3.png">
比如点击上面的按钮进行排序

**Comment by fancymax** [comment]
@HaloWang 筛选功能 不能满足要求吗？ 感觉排序意义不是非常大啊～

**Comment by HaloWang** [comment]
比如我想找一个历时最短的车呢~
可能我的需求比较独特吧，不过很多其他产品都有这个功能呢

**Comment by fancymax** [comment]
@HaloWang 好吧，后续加。

**Comment by HaloWang** [comment]
Thanks!😄
好像有其他人也提过 #74

**Comment by EGOISTK21** [comment]
我也想要点击按钮进行排序的功能，对于长途的旅客，无论是发车时间还是历时的排序都是很有用的。

**Comment by fancymax** [comment]
@EGOISTK 好的，谢谢反馈。

**Comment by fancymax** [comment]
https://github.com/fancymax/12306ForMac/commit/f6232137f2600b58bfc2b029bb40faf93eab177c
