### ISSUE TITLE
能否在release的时候把生成日志文件的代码注释？

### ISSUE THREAD

**Issue by AlphaCatMeow** [fancymax/12306ForMac#88]
每次使用完关闭应用都会在桌面生成一个.log文件。还要手动删掉。好麻烦。

**Comment by fancymax** [comment]
@normalhh 嗯，后面把它放到log文件夹里。

**Comment by fancymax** [comment]
@normalhh 
https://github.com/fancymax/12306ForMac/commit/0b2afcc925ef2b7b696a2f5d6052701936033018
