### ISSUE TITLE
有订单未付款的时候无法提交新订单(没有错误提示)

### ISSUE THREAD

**Issue by gexiaowei** [fancymax/12306ForMac#97]
最好增加一个错误提示

**Comment by fancymax** [comment]
@gexiaowei 最新版本有提示啊，你用的哪个版本？

**Comment by fancymax** [comment]
@gexiaowei    只是提示还有点问题。

![2016-10-14 13 39 34](https://cloud.githubusercontent.com/assets/844989/19376793/97d9f286-9213-11e6-9075-3ed0664cfe37.png)

**Comment by gexiaowei** [comment]
用的是这个版本
![5779020d-4af3-4a43-893c-8a95347438d8](https://cloud.githubusercontent.com/assets/2364344/19532615/08e9a5e8-966f-11e6-9824-736d13e70933.png)
